### Получение всех сотрудников
GET http://localhost:8080/employees
### Создание сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 1000
}
### Создание сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Test",
  "department": 2,
  "salary": 5000
}
### Создание сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 5000
}

### Получение зарплат всех сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employee/high-salary

### Получение сотрудников указанного отдела
GET http://localhost:8080/department/1/employees

### Получение всех сотрудников сгруппированных по отделам
GET http://localhost:8080/department/department/employees